### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by edgard** [NBonaparte/schemegen#2]
Hey, just to let you know I've created an aur package to make arch life users easier.

Here: https://aur.archlinux.org/packages/schemegen-git/

**Comment by NBonaparte** [comment]
Thanks! I wasn't expecting anyone else to be interested in the project, but it does make it much easier to install.

**Comment by edgard** [comment]
hehe, it's very useful really. thanks for the work on it! :D will close the issue, it was just so you know.
