### ISSUE TITLE
Suggestion - Feat: add option to supress hash on output

### ISSUE THREAD

**Issue by edgard** [NBonaparte/schemegen#3]
Some config files do not accept the hash and take the colors without it, it would be nice if we could disable the prefixing of # to the colors.

**Comment by NBonaparte** [comment]
Would you like it disabled individually or globally? If individually, we could do a prefix within the color token, like `#` or `!`.

**Comment by edgard** [comment]
Guess either way works! If it's globally I can just add the # on the templates and it's done.

**Comment by NBonaparte** [comment]
I've added this in 56b8dd3, which keeps the current system intact (default uses #) but allows escaping with @. I couldn't decide which character to use, so if you have a better idea, please let me know!

**Comment by edgard** [comment]
Perfect man, this is awesome! Coudn't ask for anything else. :D
